const wubRemover = require('./toyProblem');
let sampleData1 = "WUBWEWUBAREWUBWUBWUBWUBWUBTHEWUBWUBWUBWUBWUBWUBWUBWUBWUBWUBCHAMPIONSWUBWUBWUBWUBMYWUBFRIENDWUB";
let sampleData2 = "WUBWEWUBAREWUBWUBWUBWUBWUBWUBWUBTHEWUBWUBWUBCHAMPIONSWUBWUBWUBWUBMYWUBFRIENDWUB"
let sampleData3 = "WUBWEWUBAREWUBWUBWUBWUBWUBWUBWUBWUBWUBWUBWUBTHEWUBCHAMPIONSWUBWUBWUBWUBMYWUBFRIENDWUBWUBWUBWUBWUBWUBWUB"
let sampleData4 = "WUBWUBWUBWUBWUBWUBWUBWUBWUBWEWUBAREWUBWUBWUBWUBWUBTHEWUBWUBWUBWUBWUBWUBWUBCHAMPIONSWUBWUBWUBWUBWUBWUBMYWUBFRIENDWUB"

test('expect all WUBS to be gone', () => {
    expect(wubRemover(sampleData1)).toBe('WE ARE THE CHAMPIONS MY FRIEND');
    expect(wubRemover(sampleData2)).toBe('WE ARE THE CHAMPIONS MY FRIEND');
    expect(wubRemover(sampleData3)).toBe('WE ARE THE CHAMPIONS MY FRIEND');
    expect(wubRemover(sampleData4)).toBe('WE ARE THE CHAMPIONS MY FRIEND');
})